# Generated by Django 3.1.7 on 2021-03-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.PositiveSmallIntegerField(default=0)),
                ('nit_entidad', models.PositiveBigIntegerField(default=0)),
                ('nombre_recaudadora', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_convenio', models.PositiveBigIntegerField(default=0)),
                ('fecha_transmision', models.PositiveIntegerField(default=0)),
                ('secuencia_envio', models.CharField(default='', max_length=1)),
                ('fecha_vencimiento', models.PositiveIntegerField(default=0)),
                ('numero_registros', models.PositiveIntegerField(default=0)),
                ('valor_total_transacciones', models.PositiveBigIntegerField(default=0)),
                ('reservado', models.CharField(blank=True, default='', max_length=79)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.PositiveSmallIntegerField()),
                ('nit_pagador', models.CharField(blank=True, max_length=13)),
                ('nombre_pagador', models.CharField(blank=True, max_length=20)),
                ('cuenta_pagador', models.CharField(blank=True, max_length=9)),
                ('cuenta_debitar', models.CharField(blank=True, max_length=17)),
                ('tipo_transaccion', models.CharField(blank=True, max_length=2)),
                ('valor_transaccion', models.PositiveBigIntegerField()),
                ('indicador_validacion', models.CharField(blank=True, max_length=1)),
                ('referencia_1', models.CharField(blank=True, max_length=30)),
                ('referencia_2', models.CharField(blank=True, max_length=30)),
                ('fecha_vencimiento', models.PositiveIntegerField(blank=True)),
                ('periodos_facturados', models.CharField(blank=True, max_length=2)),
                ('ciclo', models.CharField(blank=True, max_length=3)),
                ('reservado', models.CharField(max_length=17)),
                ('control', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='monet.control')),
            ],
        ),
    ]
