# Generated by Django 3.1.7 on 2021-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monet', '0002_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='reservado',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
