# Generated by Django 3.1.7 on 2021-03-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monet', '0003_auto_20210327_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo_texto',
            field=models.FileField(default='', upload_to='archivos_texto'),
        ),
    ]
